name: "release"
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  luarocks-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: LuaRocks Upload
        uses: lumen-oss/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          summary: "Find, Filter, Preview, Pick. All lua, all the time."
          detailed_description: |
            A highly extendable fuzzy finder over lists.
            Built on the latest awesome features from neovim core.
            Telescope is centered around modularity, allowing for easy customization.
          dependencies: |
            plenary.nvim
          copy_directories: |
            doc
            ftplugin
            plugin
            scripts
            autoload
            data
